---
apiVersion: v1
kind: Pod
spec:
  containers:
    # ruleid: no-security-context
    - name: nginx
      image: nginx
    # ok: no-security-context
    - name: postgres
      image: postgres
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
    # ok: no-security-context
    - name: haproxy
      image: haproxy
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Pod
spec:
  # ok: no-security-context
  securityContext:
    runAsNonRoot: true
  containers:
    # ok: no-security-context
    - name: nginx
      image: nginx
    # ok: no-security-context
    - name: postgres
      image: postgres
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
    # ok: no-security-context
    - name: haproxy
      image: haproxy
