rules:
- id: run-as-non-root
  patterns:
  # Pod Security Context
  - pattern-not-inside: |
      spec:
        ...
        securityContext:
          ...
          runAsNonRoot: $VALUE
        ...
        containers:
          ...
  # Container Security Context
  - pattern-inside: |
      containers:
        ...
  - pattern-not: |
      - name: $NAME
        image: ...
        ...
        securityContext:
          ...
          runAsNonRoot: $VALUE
  - pattern: |
      - name: $NAME
        image: ...
        ...
  - focus-metavariable: $NAME
  message: >-
    Container allows for running applications as root. This can result in privilege escalation
    attacks. Add 'runAsNonRoot: true' in 'securityContext' to prevent this.
  metadata:
    references:
    - https://kubernetes.io/blog/2016/08/security-best-practices-kubernetes-deployment/
    - https://kubernetes.io/docs/concepts/policy/pod-security-policy/
    - https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html#rule-2-set-a-user
    category: security
    cwe:
    - 'CWE-250: Execution with Unnecessary Privileges'
    owasp:
    - A05:2017 - Security Misconfiguration
    - A06:2017 - Security Misconfiguration
    technology:
    - kubernetes
    subcategory:
    - audit
    likelihood: LOW
    impact: LOW
    confidence: LOW
  languages:
  - yaml
  severity: WARNING
